version: '3'

services:
  influxdb:
    image: influxdb:1.7.1-alpine
    volumes:
      - ./docker/influxdb/influxdb.conf:/etc/influxdb/infuxdb.conf:ro
      - ./docker/influxdb/data:/var/lib/influxdb
    restart: always
    command: -config /etc/influxdb/influxdb.conf

  grafana:
    image: grafana/grafana:5.3.2
    restart: always
    volumes:
      - ./docker/grafana/data:/var/lib/grafana
    ports:
      - 3000:3000/tcp

  chronograf:
    image: chronograf:1.7.3-alpine
    restart: always
    command: --influxdb-url=http://influxdb:8086 --kapacitor-url=http://kapacitor:9092/
    volumes:
      - ./docker/chronograf/data:/var/lib/chronograf
    ports:
      - 8888:8888/tcp
    depends_on:
     - influxdb

  kapacitor:
    image: kapacitor:1.5.1-alpine
    restart: always
    environment:
      - "KAPACITOR_HOSTNAME=kapacitor"
      - "KAPACITOR_INFLUXDB_0_URLS_0=http://influxdb:8086/"
    volumes:
      - ./docker/kapacitor/data:/var/lib/kapacitor
    depends_on:
     - influxdb
     - chronograf

## Service Inputs ##

  input-agent:
    build:
      context: ./plugins/input-agent
    restart: always
    volumes:
      - ./data:/opt/open-nti/data
    depends_on:
      - influxdb

  input-jti:
    build:
      context: ./plugins/input-jti/
    restart: always
    ports:
     - 50000:50000/udp
     - 50020:50020/udp
    volumes:
     - /etc/localtime:/etc/localtime:ro
    depends_on:
     - influxdb

  input-syslog:
    image: juniper/open-nti-input-syslog:latest
    restart: always
    environment:
     - "INFLUXDB_ADDR=influxdb"
     - "OUTPUT_INFLUXDB=true"
     - "OUTPUT_STDOUT=false"
    ports:
     - 6000:6000/udp
    volumes:
     - /etc/localtime:/etc/localtime:ro
    depends_on:
     - influxdb

  input-snmp:
    image: telegraf:1.8.3-alpine
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime
      - ./plugins/input-snmp/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb

  input-internal:
    image: telegraf:1.8.3-alpine
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./plugins/input-internal/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/rootfs/sys:ro
      - /proc:/rootfs/proc:ro
      - /etc:/rootfs/etc:ro
    depends_on:
     - influxdb

#networks:
#  default:
#      name: opennti
